baseURL = '/'
languageCode = 'en-us'
title = 'Wilderness Downtown'
theme = 'smol'
copyright = "Julian Yap"
paginate=5 # articles per page

[params]
mode="dark" # color-mode → light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
dateFmt = "2006-01-02 3:04PM"

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jyap808"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jyap"

# Main menu Items
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 3

# Footer
[[menu.footer]]
name = "GitHub"
url = "https://github.com/jyap808"
weight = 1 

[[menu.footer]]
name = "Twitter"
url = "https://twitter.com/jyap"
weight = 2 

# Code Highlight
[markup]
  [markup.highlight]
    style = 'catppuccin-latte'
    tabWidth = 4
