baseURL = 'https://julianyap.com/'
languageCode = 'en-us'
title = 'Wilderness Downtown'
theme = 'cactus'
copyright = "Julian Yap"
pagination.pagerSize=5 # articles per page

[params]
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
dateFmt = "2006-01-02 3:04PM"
# Smol theme
mode="dark"
# Cactus theme
tocInline = true
tagsOverview = false
colortheme="dark"
rss=true # This doesn't seem to work

[[params.social]]
  name = "github"
  link = "https://github.com/jyap808"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/julianyap"

[[params.social]]
  name = "square-letterboxd"
  link = "https://letterboxd.com/jyap8"

[[params.social]]
  name = "x-twitter"
  link = "https://x.com/jyap"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Pages"
url = "/pages"
weight = 3

[[menu.main]]
name = "Snippets"
url = "/snippets"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

# Code Highlight
[markup]
  [markup.highlight]
    style = 'catppuccin-latte'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
