baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'archie'
copyright = "© Julian Yap"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jyap808"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jyap/"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
